services:
  db:
    hostname: postgres0
    container_name: postgres0
    env_file:
      - ./config/.env.production
    image: postgres:16
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - 'db_data:/data/db'
    restart: always

  redis:
    image: 'redis:7.2.5-alpine'
    container_name: redis0
    restart: always
    env_file:
      - ./config/.env.production
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command: ["redis-server", "/etc/redis/redis.conf"]
    expose:
      - 6379
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis0/data'
      - './config/redis.conf:/etc/redis/redis.conf'

  nestapp:
    hostname: nestapp
    container_name: nestapp
    image: nestapp
    env_file:
      - ./config/.env.production
    build: .
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    restart: always

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local