# THIS DOCKERFILE IS INTENDED FOR DEVELOPMENT ENVIRONMENTS
# DO NOT USE THIS FOR PRODUCTION USAGES.

services:
  # Dev database
  postgres_data0:
    hostname: postgres0
    container_name: postgres0
    env_file:
      - ./config/.env.development
    image: postgres:16
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - 'postgres_data0:/data/db'
    restart: always
  # Testing database
  postgres_data_test0:
    hostname: postgres-test0
    container_name: postgres-test0
    image: postgres:16
    env_file:
      - ./config/.env.test
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=test
    expose:
      - 5433
    ports:
      - 5433:5432
    restart: always
  # Dev Redis
  redis0:
    image: 'redis:7.2.5-alpine'
    container_name: redis0
    restart: always
    env_file:
      - ./config/.env.development
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data0:/bitnami/redis0/data'
      - './redis.conf:/etc/redis/redis.conf'
  # Test Redis
  redis-test0:
    image: 'redis:7.2.5-alpine'
    container_name: redis-test0
    restart: always
    env_file:
      - ./config/.env.test
    command: ["redis-server", "/etc/redis/redis.conf"]
    expose:
      - 6380
    ports:
      - '6380:6379'
    volumes:
      - './redis.conf:/etc/redis/redis.conf'

volumes:
  postgres_data0:
    external: true
  redis_data0:
    driver: local