services:
  # Dev database
  postgres_data0:
    hostname: postgres0
    container_name: postgres0
    image: postgres:16
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - 'postgres_data0:/data/db'
    restart: always
  # Testing database
  postgres_data_test0:
    hostname: postgres-test0
    container_name: postgres-test0
    image: postgres:16
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=test
    expose:
      - 5433
    ports:
      - 5433:5432
    restart: always
  # Dev Redis
  redis0:
    image: 'redis:7.2.5-alpine'
    container_name: redis0
    restart: always
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data0:/bitnami/redis0/data'
  # Test Redis
  redis-test0:
    image: 'redis:7.2.5-alpine'
    container_name: redis-test0
    restart: always
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    expose:
      - 6380
    ports:
      - '6380:6379'
volumes:
  postgres_data0:
    external: true
  redis_data0:
    driver: local